config/routes.rb
Achievedby::Application.routes.draw do
  root :to => "home#index"

  devise_for :users,
   :path => "",
   :path_names  => {
       :sign_in      => "signin",
       :sign_out     => "signout",
       :sign_up      => "",
       :registration => "signup"
   },
   :controllers => {
       :sessions           => "users/sessions",
       :registrations      => "users/registrations",
       :confirmations      => "users/confirmations",
       :passwords          => "users/passwords",
       :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  devise_scope :user do
    scope "auth" do
      match ":name/destroy" => "users/omniauth_callbacks#destroy", via: :delete, as: :omniauth_callback
    end
    scope ":user_id" do
      resource :feed
    end
  end

  resources :achievements
end

app/views/shared/_flashes.haml
#flash-container
  - flash.each do |key, value|
    %div{ class: "alert-box #{key == :notice ? 'success' : 'alert'}" }= raw(value)

app/views/shared/_header.haml
%nav.top-bar
  %ul
    %li.name
      %h1= link_to "AchievedBy.com", root_path
    %li.toggle-topbar= link_to "", "javascript:void(0)"

  %section
    %ul.right
      - unless user_signed_in?
        %li.divider
        %li.has-button
          = link_to "Sign Up", "javascript:void(0)", :class => "success button signup-button", "data-reveal-id" => "signup-modal"
        %li.has-button
          = link_to "Sign In", "javascript:void(0)", :class => "button signin-button", "data-reveal-id" => "signin-modal"
      - else
        %li.has-button
          = link_to "javascript:void(0)", :class => "success button achievement-button", "data-reveal-id" => "achievement-modal" do
            %i.general.foundicon-idea
            New achievement
        %li.has-button
          = link_to feed_path(current_user), :class => "button" do
            %i.general.foundicon-page
            = current_user.username.upcase
        %li.divider
        %li.has-dropdown
          = link_to "javascript:void(0)" do
            %i.general.foundicon-settings
          %ul.dropdown{ :style => "width:200px;" }
            %li= link_to "Edit", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, :method => :delete, :data => { :confirm => "Are you sure?" }

app/views/shared/_modals.haml
- unless user_signed_in?
  #signin-modal.reveal-modal.medium
    %h2 Sign In
    %p.lead
      Not registered yet?
      &nbsp;
      = link_to "Sign Up", "javascript:void(0)", :class => "button round register-button", "data-reveal-id" => "signup-modal"
    %p
      #signin-form-container= render "users/sessions/form"
    = link_to raw("&#215;"), "javascript:void(0)", :class => "close-reveal-modal"

  #signup-modal.reveal-modal.medium
    %h2 Sign Up
    %p.lead
      Have an Account?
      = link_to "Sign In", "javascript:void(0)", :class => "button round login-button", "data-reveal-id" => "signin-modal"
    %p
      #signup-form-container= render "users/registrations/form"
    = link_to raw("&#215;"), "javascript:void(0)", :class => "close-reveal-modal"

  #reset-password-modal.reveal-modal.medium
    %h2 Reset Password
    %p.lead
      May be you need to
      = link_to "Sign Up", "javascript:void(0)", :class => "button round register-button", "data-reveal-id" => "signup-modal"
      or
      = link_to "Sign In", "javascript:void(0)", :class => "button round login-button", "data-reveal-id" => "signin-modal"
      ?
    %p
      #reset-password-form-container= render "users/passwords/new"
      = link_to raw("&#215;"), "javascript:void(0)", :class => "close-reveal-modal"
- else
  #achievement-modal.reveal-modal.xlarge
    %h2 New achievement
    %p
      #achievement-form-container= render "achievements/form"
    = link_to raw("&#215;"), "javascript:void(0)", :class => "close-reveal-modal"

app/views/shared/_providers.haml
.row
  %center
    = link_to "javascript:void(0)", "data-url" => user_omniauth_authorize_path(:facebook), :class => "button large round provider-popup-open" do
      %i.social.foundicon-facebook
      = "#{button_name} Facebook"
    = link_to "javascript:void(0)", "data-url" => user_omniauth_authorize_path(:twitter), :class => "button large round provider-popup-open" do
      %i.social.foundicon-twitter
      = "#{button_name} Twitter"