config/routes.rb
Achievedby::Application.routes.draw do
  root :to => "home#index"

  devise_for :users,
   :path => "",
   :path_names  => {
       :sign_in      => "signin",
       :sign_out     => "signout",
       :sign_up      => "",
       :registration => "signup"
   },
   :controllers => {
       :sessions           => "users/sessions",
       :registrations      => "users/registrations",
       :confirmations      => "users/confirmations",
       :passwords          => "users/passwords",
       :omniauth_callbacks => 'users/omniauth_callbacks'
   }

  devise_scope :user do
    scope "auth" do
      match ":name/destroy" => "users/omniauth_callbacks#destroy", via: :delete, as: :omniauth_callback
    end
    scope ":user_id" do
      resource :feed
    end
  end

  resources :achievements
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :user
  has_one    :video
  has_one    :picture

  attr_accessible :title, :content, :video_attributes
  accepts_nested_attributes_for :video, :reject_if => lambda { |v| v[:url].blank? }, :allow_destroy => true

  validates :title, :presence => true
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  layout false, :except => [:show]

  def create
    @achievement = current_user.achievements.build(params[:achievement])
    unless @achievement.video.nil?
      @achievement.video.user = current_user
    end
    @achievement.save

    respond_to do |format|
      format.js{ render :locals => { :achievement => @achievement } }
    end
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
  def achievement_name
    :achievement
  end

  def achievement
    @achievement ||= current_user.achievements.build
    @video = @achievement.build_video if @achievement.video.nil?
    @achievement
  end

  def video
    @video || achievement
    @video
  end

  def display_video_for(achievement)
    unless achievement.video.nil?
      video = YOUTUBE_CLIENT.video_by(achievement.video.url)
      raw video.embed_html5({:class => 'video-player', :width => '400', :height => '250', :frameborder => '1'})
      #content_tag("iframe", "", :type => "text/html", :allowscriptaccess => "always", :width => 400, :height => 250, :src => "http://www.youtube.com/embed/#{achievement.video.url}?enablejsapi=1")
    end
  end
end

app/views/achievements/_achievement.haml
.achievement-container.row
  .achievement-header.row
    %h3
      = achievement.title
  .achievement-content.row
    .row.attachment
      = display_video_for(achievement)
    .row= achievement.content
  .achievement-footer.row
    .right= "Added #{time_ago_in_words(achievement.created_at)} ago"

app/views/achievements/_form.haml
= form_for(achievement, :as => achievement_name, :url => achievements_path, :method => :post, :remote => true) do |f|
  = f.text_field :title, :placeholder => "Title"
  = error_message_on(achievement, :title, :html_tag => "small", :css_class => "error")
  = f.text_area :content
  = f.fields_for :video do |video_fields|
    = video_fields.text_field :url, :placeholder => "Video from Youtube"
    = error_message_on(video, :url, :html_tag => "small", :css_class => "error")
  %br/
  .row
    .left= f.submit "Save", :class => "success button large"
    .right= link_to "Cancel", "javascript:void(0)", :class => "secondary button large modal-cancel", "data-trigger" => "achievement-modal"

app/views/achievements/create.js.haml
- unless achievement.new_record?
  window.location = "#{root_path}"
- else
  $("#achievement-form-container").html("#{escape_javascript(render 'form')}")
  $("a.modal-cancel").bind("click", $.modal_cancel)